### ISSUE TITLE
Can't persist 100 users-UserNameIndex index is null

### ISSUE THREAD

**Issue by tarasn** [kjk/volante#1]
I tried to persist  100 users via Volante DB (version 0.9.0.0).After an attempt to read comited data the UserNameIndex equals to null. What are steps need to perform to set UserNameIndex index ?

    using System;
    using System.Collections;
    using Volante;

    namespace ConsoleApplication8
    {
        public class DatabaseRoot : Persistent
        {
            public IIndex<string, User> UserNameIndex;
        }

        public class User : Persistent
        {
            public string FullName { get; set; }
            public string Username { get; set; }

        }
        class Program
        {
            static void Main(string[] args)
            {
               

                IDatabase db = DatabaseFactory.CreateDatabase();
                db.Open(@"c:\fileinfo.dbs");

                DatabaseRoot dbRoot = null;
                if (null != db.Root)
                {
                    dbRoot = (DatabaseRoot) db.Root;
                }
                else
                {
                    // only create root the first time
                    dbRoot = new DatabaseRoot();
                    db.Root = dbRoot;
                    dbRoot.UserNameIndex = db.CreateIndex<string, User>(IndexType.Unique);
                    // changing the root marks database as modified but it's
                    // only modified in memory. Commit to persist changes to disk.
                    for (int i = 0; i < 100; i++)
                    {
                        var u = new User
                        {
                            FullName = "User" + i,
                            Username = "usrname_" + i

                        };
                        dbRoot.UserNameIndex.Put(u.Username, u);
                    }
                    
                    db.Commit();
                }

                IDictionaryEnumerator de = dbRoot.UserNameIndex.GetDictionaryEnumerator();
                string prevName = "";
                //simplified code: doesn't show the first duplicate file
                while (de.MoveNext())
                {
                    string name = (string)de.Key;
                    if (name == prevName)
                    {
                        User fe = (User)de.Value;
                        Console.WriteLine(" " + fe.FullName);
                    }
                    prevName = name;
                }

                Console.ReadLine();
            }
        }
    }

**Comment by kjk** [comment]
I noticed that you didn't call db.Close() which ensures that everything is fully written. Please try to add Close() and see if it fixes it.

**Comment by tarasn** [comment]
I added db.Close(); just before Console.ReadLine(); .The exception still occurs .

**Comment by kjk** [comment]
It's subtle but proper sequence of creating a root is:
```
                dbRoot = new DatabaseRoot();
                dbRoot.UserNameIndex = db.CreateIndex<string, User>(IndexType.Unique);
                db.Root = dbRoot;
```
When you assign `UserNameIndex`, it doesn't mark dbRoot as changed, so database doesn't know to persist it. You can also do:
```
                dbRoot = new DatabaseRoot();
                db.Root = dbRoot;
                dbRoot.UserNameIndex = db.CreateIndex<string, User>(IndexType.Unique);
                dbRoot.Modify();
```
to manually mark dbRoot object as changed.

**Comment by tarasn** [comment]
Thanks  .
dbRoot.Modify(); solved my problem
