### ISSUE TITLE
RTree overlap

### ISSUE THREAD

**Issue by dunha** [kjk/volante#5]
Hi

Thanks for the library. It seems to be exactly what I need.
I have a SQLite spatial database which I am currently using and works very well, but I would like to migrate it to a .Net option to simplify cross platform development.
I have migrated the data and after much testing managed to return query results using the RTree index. However, I found that the frustrations I was encountering were due to the much larger test rectangle required compared to the SQLite implementation. I assume this is due to the Overlap method which I wasn't able to check with my limited experience.
I am working in decimal degrees and the same data and same search point with volante using a rectangle a factor of 10 larger returns less results. I am expanding a point by a distance to create the search rectangle
Any advice would be appreciated

Duncan

**Comment by kjk** [comment]
Unfortunately, this library is no longer being developed.
